services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: docker-test-app
    volumes:
      - ./app-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000"]
      interval: 30s
      timeout: 10s 
      retries: 3 
      start_period: 30s

  db:
    image: mariadb:11
    restart: always
    container_name: docker-mariadb
    env_file:
      - ./.env
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
        start_period: 10s
        interval: 10s
        timeout: 5s
        retries: 3

volumes:
  db-data:
